### PR TITLE
Light subsys

### LINKED ISSUE #11: Rewrite sensors and actuators to use pubsub design pattern
- [x] send messages to relevant thread on Sensor.collect() (Humidity and Light subsystem)
- [x] send messages to relevant thread on Sensor.collect()
- [x] Create data structure SensorData, and use it for sending Sensor data over pubsub
- [x] Subscirbe to relevant threads on data analysis susbsytems (E.g. seperate classes for each "data type", monitoring the current state and sending messages over pubsub to control actuators)
- [x] Subscribe to relevant threads on actuator systems, and interpret control commands accordingly

### LINKED ISSUE #17: Create a DB for storing sensor data
- [x] Select a DB to use: (mySQL, SQLite, influxDB, MariaDB)
- [x] Create a Python wrapper for controlling the DB
- [x] Add pubsub listeners on sensor data updates, store them in the DB

### LINKED ISSUE #18: Add light system draft: sensor+actuator

### PR DESCRIPTION
**Pull request by Willmish**
# Description
This PR adds Draft for the light system (HW to be debugged, the mosfet may be burned? Sometimes works, sometimes doesn't), and a draft implementation of a sqlite3 database, which listens on, on new data and stores it. Also restructured pubsub topics to have hierarchy (so DB can listen in on all sensor data in a single listener).

- Adds sensor control and actuator (without PWM automated by a PID controller).
- Adds Draft implementation of a DB manager `database` module.

## Type of change
- [ ] New features, to be tested on HW

## Issues
Closes #17 Closes #11 Closes #18

### CODE REVIEW

**Comment by ikerexxe** [comment]
If you are interested I've proposed a [fix](https://github.com/grantmcconnaughey/lintly-flake8-github-action/pull/16) for the execution error from flake8.

**Comment by Willmish** [comment]
> If you are interested I've proposed a [fix](https://github.com/grantmcconnaughey/lintly-flake8-github-action/pull/16) for the execution error from flake8.

Hi @ikerexxe, thanks for suggesting the fix! Glad to see others are using same tools and working on them :). I was planning on fixing this myself earlier, glad someone found an easy workaround. I incorporated your fix into my fork for python3.10: https://github.com/Willmish/lintly-flake8-github-action.

**Comment by ikerexxe** [comment]
> Hi @ikerexxe, thanks for suggesting the fix! Glad to see others are using same tools and working on them :). I was planning on fixing this myself earlier, glad someone found an easy workaround. I incorporated your fix into my fork for python3.10: https://github.com/Willmish/lintly-flake8-github-action.

You're welcome. I hope the original writer of the tool dedicates some time to review the existing PRs and have something consistent in his repository.

**Review by angela24680403 — APPROVED** [review]
Looking good!

**Pull request merged**
